### ISSUE TITLE
Undefined after source Arrow

### ISSUE THREAD

**Issue by jacovinus** [metrico/grafana-flow#21]
The source arrow is presenting an ´undefined´ at every instance. Shown at image below:

![Screenshot 2023-07-10 112750](https://github.com/metrico/grafana-flow/assets/30432825/de430d4f-5be4-410e-a60b-de8a0b3c6187)
This undefinded should be removed from source code, as is information not found or not shown.

**Comment by RFbkak37y3kIY** [comment]
fixed
