### ISSUE TITLE
Top labels not matching with vertical lines

### ISSUE THREAD

**Issue by jacovinus** [metrico/grafana-flow#22]
At resizing flow at its container, the top Labels goes missaligned with the vertical lines as seen below:

![Screenshot 2023-07-10 113602](https://github.com/metrico/grafana-flow/assets/30432825/038c7210-a609-49ab-a37d-f25fe3ffc0af)
Possible solutions: 
- (Ideally) resize according to container size
- (Not ideal) block somehow the container size

**Comment by RFbkak37y3kIY** [comment]
fixed
