### ISSUE TITLE
strange coloring of call flows

### ISSUE THREAD

**Issue by tsearle** [metrico/grafana-flow#42]
### Describe the bug.

when viewing a call flow with only 2 callids, I see alot more than 2 colour

<img width="1146" alt="Screenshot 2023-11-09 at 10 17 36" src="https://github.com/metrico/qryn-view/assets/4540323/36a54e46-2580-4722-8eec-f9392c264d21">

### Reproduction

filter for 2 sip call ids

### Application version

10.0.8

**Comment by lmangani** [comment]
Thanks for the report @tsearle 

An initial note - the grafana flow plugin is NOT exclusive to SIP sessions or messages, and it's rather generic. The method used to define the color depends on the object features and is configurable from the panel preferences:

![image](https://github.com/metrico/grafana-flow/assets/1423657/4386dea6-f18a-4296-b1e9-5c70d49157d9)


By default the HOMER10 demo uses: `src_ip`, `dst_ip`, `type`

**Comment by tsearle** [comment]
call-id is a derrived field, and currently can't be used for colour

**Comment by lmangani** [comment]
Anything that's part of the message would have to be extracted/matched with Regex. We'll think of an additional method to allow it with the extra processing on the client-side.

**Comment by lmangani** [comment]
Closing in favour of https://github.com/metrico/grafana-flow/issues/44
