### ISSUE TITLE
SIP over TCP is malformed in pcap export

### ISSUE THREAD

**Issue by tsearle** [metrico/grafana-flow#58]
when exporting a callflow to pcap, UDP messages are ok, but TCP messages do not display properly

<img width="1394" alt="Screenshot 2024-03-21 at 10 03 26" src="https://github.com/metrico/grafana-flow/assets/4540323/258fc683-8164-49a1-ba2d-da9886faf5d5">

**Comment by lmangani** [comment]
@tsearle https://github.com/metrico/grafana-flow/releases/tag/v10.0.12 should have a fix for this issue ready to test

**Comment by lmangani** [comment]
Closing as resolved
