### ISSUE TITLE
issue in displaying sip packets in 10.0.11

### ISSUE THREAD

**Issue by tsearle** [metrico/grafana-flow#59]
when I click on a sip message in a callflow diagram, I see the information for the packet that comes AFTER the one I selected...

e.g. when I click an INVITE request, I see the 100 Trying that comes immediately after it in the callflow instead

**Comment by lmangani** [comment]
Thanks for the report @tsearle I don't know how this was missed, fix in progress!

**Comment by lmangani** [comment]
@tsearle https://github.com/metrico/grafana-flow/releases/tag/v10.0.12 should fix this problem
