### ISSUE TITLE
Filtering for invite Packets is not working.

### ISSUE THREAD

**Issue by naqashsaeed** [metrico/grafana-flow#68]
Hi, I have tested new version of Homer-10. So on filtering when i uncheck the invite packet it still shows invite packet in call-flow dashboard as shown below.
![image](https://github.com/metrico/grafana-flow/assets/110665986/d3a6ca45-8993-4652-90ef-d8f4687c3861)

For Reproducing this issue, you just need to click on filters and uncheck Invite. You still see invite packet in call-flow dashboard.

**Comment by AlexeyOplachko** [comment]
This is an issue specifically with homer-10-scene, not present in dashboards, and is just a simple config issue. 
Fixed in: https://github.com/AlexeyOplachko/Homer10-scene/commit/10fcfa762c4985519321b1cb2ab68e4be21403d0
